### ISSUE TITLE
feat: filter functionality on `Explore` page

### ISSUE THREAD

**Issue by tokitouq** [tokitouq/v3-coreproject-ui#603]
![Screenshot from 2023-08-19 22-08-57](https://github.com/tokitou-san/CoreProject-V3-UI/assets/114811070/0b603a42-b49a-4c3c-9687-9fa93331aaf3)

**Comment by baseplate-admin** [comment]
What exactly are you looking for. Update me and i will do it

**Comment by tokitou-san** [comment]
> What exactly are you looking for. Update me and i will do it

A combobox with custom function

- Shows on input active
- Search functionality ( filter )
- Shows selected items with something like tick mark ( current approach )
- On select: filter again and shows on input box with custom logic

Thats all for now.
anyways we cant use tippy like this for this case, or we need to wait for skele popup refactor.
Or create custom?

**Comment by tokitouq** [comment]
Fixed on repo:
https://github.com/baseplate-admin/CoreProject
