### ISSUE TITLE
refactor: `Comment` section to support nested tree structure

### ISSUE THREAD

**Issue by baseplate-admin** [tokitouq/v3-coreproject-ui#676]
https://github.com/tokitou-san/CoreProject-V3-UI/blob/fb4161940e45b08aa7998b365779d1f82c3c3a0c/src/lib/components/shared/comment.svelte#L1-L113

**Comment by baseplate-admin** [comment]
Yes @tokitou-san can you do it?

**Comment by tokitou-san** [comment]
> Yes @tokitou-san can you do it?

Yea, if you aren't working on this - yes

**Comment by tokitouq** [comment]
Fixed with:
https://github.com/baseplate-admin/CoreProject/blob/master/backend/django_core/static_src/components/minor/Comment/CommetBlock.svelte
